name: Build docs and publish on GitHub Pages

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-env
      - name: Build docs
        run: poetry run poe docs
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true
